# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(401, 266)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 30, 351, 191))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.L_name = QtWidgets.QLabel(self.frame)
        self.L_name.setGeometry(QtCore.QRect(74, 30, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.L_name.setFont(font)
        self.L_name.setObjectName("L_name")
        self.E_name = QtWidgets.QLineEdit(self.frame)
        self.E_name.setGeometry(QtCore.QRect(70, 60, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.E_name.setFont(font)
        self.E_name.setText("")
        self.E_name.setObjectName("E_name")
        self.Btn_Save = QtWidgets.QPushButton(self.frame)
        self.Btn_Save.setGeometry(QtCore.QRect(80, 120, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Btn_Save.setFont(font)
        self.Btn_Save.setObjectName("Btn_Save")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.L_name.setText(_translate("Dialog", "Enter Team name"))
        self.Btn_Save.setText(_translate("Dialog", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
